services:
  hannibaltutu-miner:
    build:
      context: .
      args:
        XMRIG_REF: "master"
        UPSTREAM_REFRESH: "local-build"
    image: hannibaltutu-nas-miner:local
    container_name: hannibaltutu-miner
    restart: unless-stopped
    environment:
      WALLET: "YOUR_MONERO_WALLET_HERE"
      WORKER: "My-NAS"
      THREADS: "3"
      POOL: "gulf.moneroocean.stream:10128"
      PRINT_TIME: "60"
