services:
  hannibaltutu-miner:
    image: ghcr.io/thelion81/hannibaltutu-nas-miner:1.0.0
    container_name: hannibaltutu-miner
    restart: unless-stopped
    pull_policy: always
    environment:
      # 1) VUL HIER JE EIGEN MONERO-WALLET IN
      WALLET: "VUL_HIER_JE_MONERO_WALLET_IN"

      # 2) Geef je NAS/miner een herkenbare naam
      WORKER: "Mijn-NAS"

      # 3) Aantal CPU-threads. Voor een DS224+ is 3 een prima startpunt.
      THREADS: "3"

      # Voor beginners: gewoon laten staan
      POOL: "gulf.moneroocean.stream:10128"
      PRINT_TIME: "60"
